name: Update develop

on:
  pull_request:
    branches:
      - develop
    types:
      - closed
jobs:
  compile:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && (startsWith(github.event.pull_request.head.ref, 'feature/') || startsWith(github.event.pull_request.head.ref, 'hotfix/'))
    strategy:
      matrix:
        java: [11]
    name: Build project with Java ${{ matrix.java }}
    env:
      DOCKER_REPO_URL: ${{ secrets.DOCKER_REPO_URL }}
      GITHUB_TOKEN: ${{ secrets.BB_GITHUB_PACKAGES_PAT }}
      BB_MAVEN_USERNAME: ${{ secrets.BB_MAVEN_USERNAME }}
      BB_MAVEN_PASSWORD: ${{ secrets.BB_MAVEN_PASSWORD }}
      GLOBAL_USER: ${{ secrets.GLOBAL_USER }}
      GLOBAL_EMAIL: ${{ secrets.GLOBAL_EMAIL }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup java ${{ matrix.java }} for sonar
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v4
        with:
          repositories: '[{ "id": "Backbase Repository", "url": "https://repo.backbase.com/repo" }]'
          plugin_repositories: '[{ "id": "Backbase Repository", "url": "https://repo.backbase.com/repo" }]'
          servers: '[{ "id": "Backbase Repository", "username": "${BB_MAVEN_USERNAME}", "password": "${BB_MAVEN_PASSWORD}" }]'

        # Bump patch snapshot and delete the source branch
      - name: Bump patch snapshot version
        run: |
          mvn build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}-SNAPSHOT versions:commit
           git config --global user.email ${GLOBAL_EMAIL}
           git config --global user.name ${GLOBAL_USER}
           git add --all
           git commit -m "Bumping SNAPSHOT Version"
           git push
           echo "::set-output delete_branch=${{ github.event.pull_request.head.ref }}"
           git push origin --delete ${{ github.event.pull_request.head.ref }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get AWS ECR credentials
        id: ecr-credentials
        run: |
          echo "::set-output name=username::AWS"
          echo "::set-output name=password::`aws ecr get-login-password --region ${{ secrets.AWS_REGION }}`"

      - name: Build docker image
        run: mvn clean package -Pdocker-image -Pno-scs -Dmaven.test.skip -Djib.to.auth.username=${{ steps.ecr-credentials.outputs.username }}  -Djib.to.auth.password=${{ steps.ecr-credentials.outputs.password }}
