name: Build and push to ECR

on:
  push:
    branches: [ develop ]

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8 ]
    name: Build Project Java ${{ matrix.java }} with tests execution
    env:
      DOCKER_REPO_URL: ${{ secrets.DOCKER_REPO_URL }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_PROJECT: ${{ github.event.repository.name }}
      BB_MAVEN_USERNAME: ${{ secrets.BB_MAVEN_USERNAME }}
      BB_MAVEN_PASSWORD: ${{ secrets.BB_MAVEN_PASSWORD }}
      BB_GITHUB_PACKAGES_USER: ${{ secrets.BB_GITHUB_PACKAGES_USER }}
      BB_GITHUB_PACKAGES_PAT: ${{ secrets.BB_GITHUB_PACKAGES_PAT }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - uses: actions/checkout@master

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup java 11 for sonar
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v4
        with:
          repositories: '[{ "id": "Backbase Repository", "url": "https://repo.backbase.com/repo" }, { "id": "github", "url": "https://maven.pkg.github.com/backbase-alm-pl/mambu-clients" }]'
          plugin_repositories: '[{ "id": "Backbase Repository", "url": "https://repo.backbase.com/repo" }]'
          servers: '[{ "id": "Backbase Repository", "username": "${BB_MAVEN_USERNAME}", "password": "${BB_MAVEN_PASSWORD}" }, { "id": "github", "username": "${BB_GITHUB_PACKAGES_USER}", "password": "${BB_GITHUB_PACKAGES_PAT}" }]'

      - name: Run tests and Sonar Cloud check
        run: mvn verify sonar:sonar
        env:
          SONAR_ORGANIZATION: ${GITHUB_REPOSITORY_OWNER}
          SONAR_PROJECT_KEY: ${GITHUB_REPOSITORY_OWNER}_${GITHUB_PROJECT}

      - name: Setup java ${{ matrix.java }} for build
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v4
        with:
          repositories: '[{ "id": "Backbase-Repo", "url": "https://repo.backbase.com/repo" }, { "id": "github", "url": "https://maven.pkg.github.com/backbase-alm-pl/mambu-clients" }]'
          plugin_repositories: '[{ "id": "Backbase-Repo", "url": "https://repo.backbase.com/repo" }]'
          servers: '[{ "id": "Backbase-Repo", "username": "${BB_MAVEN_USERNAME}", "password": "${BB_MAVEN_PASSWORD}" }, { "id": "github", "username": "${BB_GITHUB_PACKAGES_USER}", "password": "${BB_GITHUB_PACKAGES_PAT}" }]'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get AWS ECR credentials
        id: ecr-credentials
        run: |
          echo "::set-output name=username::AWS"
          echo "::set-output name=password::`aws ecr get-login-password --region ${{ secrets.AWS_REGION }}`"

      - name: Build docker image
        run: mvn clean package -Pdocker-image -Pno-scs -Dmaven.test.skip -Djib.to.auth.username=${{ steps.ecr-credentials.outputs.username }}  -Djib.to.auth.password=${{ steps.ecr-credentials.outputs.password }}
