name: Start-Feature

on:
  workflow_dispatch:
    inputs:
      storyNumber:
        description: 'Story Number'
        required: true
        default: 'PROMO-'
      featureName:
        description: 'Feature Name'
        required: true
        default: 'feature-name'
jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11]
    name: Start new feature
    env:
      DEVOPS_CICD_ECR_BASE_URL: ${{ secrets.DEVOPS_CICD_ECR_BASE_URL }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BB_USERNAME: ${{ secrets.BB_USERNAME }}
      BB_PASSWORD: ${{ secrets.BB_PASSWORD }}
      BB_GITHUB_PACKAGES_USER: botuser
      BB_GITHUB_PACKAGES_PAT: ${{ secrets.BB_GITHUB_PACKAGES_PAT }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            ${{ runner.os }}-

      - name: Setup java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v4
        with:
          repositories: '[{ "id": "Backbase Repository", "url": "https://repo.backbase.com/repo" }, { "id": "github", "url": "https://maven.pkg.github.com/${GITHUB_REPOSITORY_OWNER}/mambu-clients" }]'
          plugin_repositories: '[{ "id": "Backbase Repository", "url": "https://repo.backbase.com/repo" }]'
          servers: '[{ "id": "Backbase Repository", "username": "${BB_USERNAME}", "password": "${BB_PASSWORD}" }, { "id": "github", "username": "${BB_GITHUB_PACKAGES_USER}", "password": "${BB_GITHUB_PACKAGES_PAT}" }]'

      - name: Set git username and email
        run: |
          git config --global user.email "bot@backbase.com"
          git config --global user.name "Release BOT"

      - name: Start new Feature ${{ github.event.inputs.storyNumber }}-${{ github.event.inputs.featureName }}
        run: mvn -B gitflow:feature-start -DpushRemote=true -DskipFeatureVersion=true -DfeatureName=${{ github.event.inputs.storyNumber }}-${{ github.event.inputs.featureName }}
