name: Start-Feature

on:
  workflow_dispatch:
    inputs:
      storyNumber:
        description: 'Story Number'
        required: true
        default: 'PROMO-'
      featureName:
        description: 'Feature Name'
        required: true
        default: 'feature-name'
jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11]
    name: Start new feature
    env:
      GITHUB_TOKEN: ${{ secrets.BB_GITHUB_PACKAGES_PAT }}
      BB_MAVEN_USERNAME: ${{ secrets.BB_MAVEN_USERNAME }}
      BB_MAVEN_PASSWORD: ${{ secrets.BB_MAVEN_PASSWORD }}
      GLOBAL_USER: ${{ secrets.GLOBAL_USER }}
      GLOBAL_EMAIL: ${{ secrets.GLOBAL_EMAIL }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v4
        with:
          repositories: '[{ "id": "Backbase Repository", "url": "https://repo.backbase.com/repo" }]'
          plugin_repositories: '[{ "id": "Backbase Repository", "url": "https://repo.backbase.com/repo" }]'
          servers: '[{ "id": "Backbase Repository", "username": "${BB_MAVEN_USERNAME}", "password": "${BB_MAVEN_PASSWORD}" }]'

      - name: Set git username and email
        run: |
          git config --global user.email ${GLOBAL_EMAIL}
          git config --global user.name ${GLOBAL_USER}

      - name: Start new Feature ${{ github.event.inputs.storyNumber }}-${{ github.event.inputs.featureName }}
        run: mvn -B gitflow:feature-start -DpushRemote=true -DskipFeatureVersion=true -DfeatureName=${{ github.event.inputs.storyNumber }}-${{ github.event.inputs.featureName }}
