name: Pull-Request-Check

#
#   IMPORTANT TO KNOW
#
# - This workflow runs whenever new changes are pushed to an existing Pull Request
# - Runs on 'master', 'develop', 'release/*' and 'hotfix/*' branches
#

on:
  pull_request:
    branches: [ develop, master, release/*, hotfix/*]
jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11]
    name: Build project with Java ${{ matrix.java }} ensure quality and security gates
    env:
      GITHUB_PROJECT: ${{ github.event.repository.name }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BB_MAVEN_USERNAME: ${{ secrets.BB_MAVEN_USERNAME }}
      BB_MAVEN_PASSWORD: ${{ secrets.BB_MAVEN_PASSWORD }}
      BB_GITHUB_PACKAGES_USER: ${{ secrets.BB_GITHUB_PACKAGES_USER }}
      BB_GITHUB_PACKAGES_PAT: ${{ secrets.BB_GITHUB_PACKAGES_PAT }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Maven Setup settings.xml with BB credentials
        uses: whelk-io/maven-settings-xml-action@v4
        with:
          repositories: '[{ "id": "Backbase Repository", "url": "https://repo.backbase.com/repo" }, { "id": "github", "url": "https://maven.pkg.github.com/backbase-alm-pl/mambu-clients" }]'
          plugin_repositories: '[{ "id": "Backbase Repository", "url": "https://repo.backbase.com/repo" }]'
          servers: '[{ "id": "Backbase Repository", "username": "${BB_MAVEN_USERNAME}", "password": "${BB_MAVEN_PASSWORD}" }, { "id": "github", "username": "${BB_GITHUB_PACKAGES_USER}", "password": "${BB_GITHUB_PACKAGES_PAT}" }]'

      - name: Run tests and Sonar Cloud check
        run: mvn verify sonar:sonar
        env:
          SONAR_ORGANIZATION: ${GITHUB_REPOSITORY_OWNER}
          SONAR_PROJECT_KEY: ${GITHUB_REPOSITORY_OWNER}_${GITHUB_PROJECT}
